### ISSUE TITLE
Which commit is used to build test-fork docker image?

### ISSUE THREAD

**Issue by datluongductuan** [0xPolygonHermez/zkevm-contracts#107]
Hi all, I'm customize some configuration in this image
[https://hub.docker.com/layers/hermeznetwork/geth-zkevm-contracts/test-fork/images/sha256-7373d0f383f31b7af31210cd4709ac5294d26287b82a03674cfd39f6b4716437?context=explore…](https://t.co/yAw9y1gMaX)

But idk which commit to be build to this image, could you give me some information, thanks so much!

**Comment by invocamanman** [comment]
you can/should build it with the last main commit
