### ISSUE TITLE
How to fix the ERC777 re-entrancy attack?

### ISSUE THREAD

**Issue by 3for** [0xPolygonHermez/zkevm-contracts#108]
The first weakness mentioned in [Hexens audit report](https://github.com/0xPolygonHermez/zkevm-contracts/blob/main/audits/Hexens_Polygon_zkEVM_PUBLIC_27.02.23.pdf)：
![屏幕快照 2023-03-21 上午11 36 38](https://user-images.githubusercontent.com/30716372/226512132-af06b5b2-d7c4-43d0-ac99-5788e8fe441e.png)

But the [codes](https://github.com/0xPolygonHermez/zkevm-contracts/blob/main/contracts/PolygonZkEVMBridge.sol#L193) are still the same:
```
               // In order to support fee tokens check the amount received, not the transferred
                uint256 balanceBefore = IERC20Upgradeable(token).balanceOf(
                    address(this)
                );
                IERC20Upgradeable(token).safeTransferFrom(
                    msg.sender,
                    address(this),
                    amount
                );
                uint256 balanceAfter = IERC20Upgradeable(token).balanceOf(
                    address(this)
                );

                // Override leafAmount with the received amount
                leafAmount = balanceAfter - balanceBefore;
```
I want to learn how we fixed this attack?

**Comment by invocamanman** [comment]
Hey!, This type of attacks usually are solved with a reentrancy lib, and that exactly what we add in the function: 
https://github.com/0xPolygonHermez/zkevm-contracts/blob/main/contracts/PolygonZkEVMBridge.sol#L149
You can check more info about this in the `nonReentrant` modifier here: https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/security/ReentrancyGuard.sol#L50

**Comment by 3for** [comment]
@invocamanman Thanks a lot.
