### ISSUE TITLE
How to solve the problem when users submit invalid transactions

### ISSUE THREAD

**Issue by Federico2014** [0xPolygonHermez/zkevm-contracts#120]
I see the `forceBatch` function does not check the validity of transactions, how to solve the problem when users submit invalid transactions, is there any way to revert it?
https://github.com/0xPolygonHermez/zkevm-contracts/blob/b1cefea1431e59b2121e543b786b93af99e859f4/contracts/PolygonZkEVM.sol#L1018

```
function forceBatch(
        bytes calldata transactions,
        uint256 maticAmount
    )
```

**Comment by Federico2014** [comment]
The `sequenceBatches` does not check the validity of transactions either.

**Comment by krlosMata** [comment]
All data submitted in `forceBatch` and in `sequenceBatches` must be processed by the [zkevm-rom](https://github.com/0xPolygonHermez/zkevm-rom) either the data is a valid transaction or just random data or invalid transaction.
In the `zkevm-rom`, all data is parsed [here](https://github.com/0xPolygonHermez/zkevm-rom/blob/main/main/load-tx-rlp.zkasm#L2) and processed [here](https://github.com/0xPolygonHermez/zkevm-rom/blob/main/main/process-tx.zkasm).
Therefore, in the rom we handle and check the validity of the transactions

**Comment by Federico2014** [comment]
> All data submitted in `forceBatch` and in `sequenceBatches` must be processed by the [zkevm-rom](https://github.com/0xPolygonHermez/zkevm-rom) either the data is a valid transaction or just random data or invalid transaction. In the `zkevm-rom`, all data is parsed [here](https://github.com/0xPolygonHermez/zkevm-rom/blob/main/main/load-tx-rlp.zkasm#L2) and processed [here](https://github.com/0xPolygonHermez/zkevm-rom/blob/main/main/process-tx.zkasm). Therefore, in the rom we handle and check the validity of the transactions

Thank you so much for your reply,  this is quite a sophisticated design,  I get it.

**Comment by Federico2014** [comment]
> All data submitted in `forceBatch` and in `sequenceBatches` must be processed by the [zkevm-rom](https://github.com/0xPolygonHermez/zkevm-rom) either the data is a valid transaction or just random data or invalid transaction. In the `zkevm-rom`, all data is parsed [here](https://github.com/0xPolygonHermez/zkevm-rom/blob/main/main/load-tx-rlp.zkasm#L2) and processed [here](https://github.com/0xPolygonHermez/zkevm-rom/blob/main/main/process-tx.zkasm). Therefore, in the ROM we handle and check the validity of the transactions

I think someone may be able to submit the `forceBatch` directly by modifying the `zkevm-node` logic,  circumventing the `zkevm-rom` processing,  which will interrupt the regular operation of the `PolygonZkEVM` contract.  Do you think it is possible?

**Comment by krlosMata** [comment]
> I think someone may be able to submit the `forceBatch` directly by modifying the `zkevm-node` logic, circumventing the `zkevm-rom` processing, which will interrupt the regular operation of the `PolygonZkEVM` contract. Do you think it is possible?

The idea is that the `forceBatch` could be submitted by anyone since it is a mechanism to bypass the `sequencer`. Hence, we achieve censorship resistant in L2 in case the `sequencer` performs any kind of DoS to any user or contracts or transaction type.
All transactions submitted by the `sequencer` or submitted via `forceBatch` must be processed by the `zevm-rom` logic since it is forced by the smart contract by hashing the transaction data, which is added to the public input of the zk-proof so it is mandatory to process exactly that data in the `zkevm-rom`.
The protocol is designed in a way that there the `zkevm-rom` must process all the data that is posted as data-availability.

**Comment by Federico2014** [comment]
> > I think someone may be able to submit the `forceBatch` directly by modifying the `zkevm-node` logic, circumventing the `zkevm-rom` processing, which will interrupt the regular operation of the `PolygonZkEVM` contract. Do you think it is possible?
> 
> The idea is that the `forceBatch` could be submitted by anyone since it is a mechanism to bypass the `sequencer`. Hence, we achieve censorship resistant in L2 in case the `sequencer` performs any kind of DoS to any user or contracts or transaction type. All transactions submitted by the `sequencer` or submitted via `forceBatch` must be processed by the `zevm-rom` logic since it is forced by the smart contract by hashing the transaction data, which is added to the public input of the zk-proof so it is mandatory to process exactly that data in the `zkevm-rom`. The protocol is designed in a way that there the `zkevm-rom` must process all the data that is posted as data-availability.


From the following logic, anyone can trigger the `forceBatch` function directly, and submit the invalid transaction, even if they can not pass the subsequent  `zkevm-rom` verification.
```
    function forceBatch(
        bytes calldata transactions,
        uint256 maticAmount
    ) public isForceBatchAllowed ifNotEmergencyState {
        // Calculate matic collateral
        uint256 maticFee = getForcedBatchFee();

        if (maticFee > maticAmount) {
            revert NotEnoughMaticAmount();
        }

        if (transactions.length > _MAX_FORCE_BATCH_BYTE_LENGTH) {
            revert TransactionsLengthAboveMax();
        }

        matic.safeTransferFrom(msg.sender, address(this), maticFee);

        // Get globalExitRoot global exit root
        bytes32 lastGlobalExitRoot = globalExitRootManager
            .getLastGlobalExitRoot();

        // Update forcedBatches mapping
        lastForceBatch++;

        forcedBatches[lastForceBatch] = keccak256(
            abi.encodePacked(
                keccak256(transactions),
                lastGlobalExitRoot,
                uint64(block.timestamp)
            )
        );

        if (msg.sender == tx.origin) {
            // Getting the calldata from an EOA is easy so no need to put the `transactions` in the event
            emit ForceBatch(lastForceBatch, lastGlobalExitRoot, msg.sender, "");
        } else {
            // Getting internal transaction calldata is complicated (because it requires an archive node)
            // Therefore it's worth it to put the `transactions` in the event, which is easy to query
            emit ForceBatch(
                lastForceBatch,
                lastGlobalExitRoot,
                msg.sender,
                transactions
            );
        }
    }
```

**Comment by krlosMata** [comment]
There is a two-step model:
- first, `transaction data` is posted: either by the sequencer or via `forceBatch`
- second, `transaction data` must be verified in the `verifyBatchesTrustedAggregator` or `verifyBatches` functions since those are the only function that can update the `L2 stare root` in L1
  - those transactions includes the `verifier` which will ensure that `transaction data` has been processed deterministically according to the `zk-rom`
  - `zk-rom` is not only EVM compatible but also can process invalid transactions (invalid `transaction data` and intrinsic checks not being satisfied)

**Comment by Federico2014** [comment]
> There is a two-step model:
> 
> * first, `transaction data` is posted: either by the sequencer or via `forceBatch`
> * second, `transaction data` must be verified in the `verifyBatchesTrustedAggregator` or `verifyBatches` functions since those are the only function that can update the `L2 stare root` in L1
>   
>   * those transactions includes the `verifier` which will ensure that `transaction data` has been processed deterministically according to the `zk-rom`
>   * `zk-rom` is not only EVM compatible but also can process invalid transactions (invalid `transaction data` and intrinsic checks not being satisfied)

Thank you so much for your reply.  For the invalid transactions, will `zk-rom`  just return error, leaving the transaction discarded, or process the transaction and return the failed receipt？

**Comment by krlosMata** [comment]
The `zk-rom` will just return that the transaction has been invalid, so the state has not been changed.
For example in [here](https://github.com/0xPolygonHermez/zkevm-rom/blob/main/main/process-tx.zkasm#L531)

**Comment by Federico2014** [comment]
Thank you so much, I get it.
