### ISSUE TITLE
Docker Deployment script throwing with latest version of docker compose v2

### ISSUE THREAD

**Issue by adirola** [0xPolygonHermez/zkevm-contracts#128]
Docker Deployment script throwing with latest version of docker compose v2
## Description
The current docker deployment script will not work with docker compose v2 installed and throws an error of unknown command "docker-compose"

## Your environment
- Linux (ubuntu 20.04).
- main.
- Running Locally.

## Steps to reproduce
- On running the docker build command "npm run docker:contracts" the deploy-docker.sh script throws the error that docker-compose command is not recognized.
- The issue is in deploy-docker.sh script which works with docker-compose version v1 not with v2.
- Which commands triggered the issue: npm run docker:contracts.

## Expected behavior
- We should be able to successfully create a docker image.
- Script throws error.

## Proposed solution
Either restrict the docker-compose version to be used or update the script to latest docker compose command

I could not find a contribution guide so opened a pull request with the above mentioned change. Would be happy to learn more about this and take this forward

**Comment by invocamanman** [comment]
Thanks for opening yourself a PR about this ^^
https://github.com/0xPolygonHermez/zkevm-contracts/pull/129
