### ISSUE TITLE
[Inquiry] How to properly make a claimAsset call

### ISSUE THREAD

**Issue by exfinen** [0xPolygonHermez/zkevm-contracts#214]
I'm developing a bridge/claim library and trying to claim an asset this bridged asset from Cardona Testnet:
https://sepolia.etherscan.io/tx/0x8f776c17ad4c285f4192bfe19f73b49a6cc6605e94b0ddfda43e7e9f340bf140#eventlog

sent from `0x13b58ad52dd0092B29bf4B061D55AE6f973614F6`, but I haven't been able to make a successful `claimAsset` call so far.

From the event log of the `bridgeAsset` call, I obtained
- depositCount : `10255`
- mainnetExitRoot: `0xa78ac5e0aa87b03a27e0447675933a399f771a9bf6b8bbc040df536f1ed9a932`
- rollupExitRoot: `0xf55be3aafef8e00498fa97ac5f18a6e2fa5bbd45d451ad10eb6f20c405088b35`

and from `zkevm-bridge-service` (https://bridge-api.cardona.zkevm-rpc.com), I obtained
- globalIndex: `18446744073709561871` (by calling `bridges/0x13b58ad52dd0092B29bf4B061D55AE6f973614F6` with `params { dest_addr: '0x13b58ad52dd0092B29bf4B061D55AE6f973614F6', offset: 0, limit: 5 }`)
- smtProofLocalExitRoot (by calling `merkle-proof` with `params { deposit_cnt: 10255, net_id: 0 }`)
- smtProofRollupExitRoot (by calling `merkle-proof` with `params { deposit_cnt: 10255, net_id: 0 }`)

Then I call claimAsset on `PolygonZkEVMBridgeV2.sol` deployed at `0x528e26b25a34a4A5d0dbDa1d57D318153d2ED58`.

For other parameters of `claimAsset`, I used
- originNetwork = `0`
- originTokenAddress = `ethers.ZeroAddress`
- destinationNetwork = `1`
- destinationAddress = `0x13b58ad52dd0092B29bf4B061D55AE6f973614F6`
- meta data = `Uint8Array(0) (empty byte vector)`

and my `claimAsset` calls fail as in:
https://cardona-zkevm.polygonscan.com/tx/0x084ad1caec223aa4ccb4f2e36ba7bdca6bbc440693a62fdf6859e05fa2980733

Could somebody point out where I'm making mistakes?

**Comment by praetoriansentry** [comment]
My guess is that you're trying to claim a tx that has already been claimed?

Your [failing claim](https://cardona-zkevm.polygonscan.com/tx/0x084ad1caec223aa4ccb4f2e36ba7bdca6bbc440693a62fdf6859e05fa2980733) is in block 1321823. The deposit that you were trying to claim was [previously claimed](https://cardona-zkevm.polygonscan.com/tx/0x0dd9f37827df404835ec1f9d8c654f9f0683969a9a0c544fb684c13ed01f6d30) in block 1320510. You can compare your tx to the tx that worked, and it appears that everything is identical except one is going to `0x13b58ad52dd0092B29bf4B061D55AE6f973614F6` and the other is going to `0x9AF3049dD15616Fd627A35563B5282bEA5C32E20`. If you replace that address in the tx input, they are byte for byte equivalent, so I think your library works just fine.

![image](https://github.com/0xPolygonHermez/zkevm-contracts/assets/429588/ebf2fed2-ed6e-4886-a67c-e40bc9df7cfb)

**Comment by exfinen** [comment]
Thank you for your explanation. Now I understood that I don't need to call `claimAsset` by myself,
But instead some periodically running process includes my bridged asset to a transaction batch, and `0xEaBCC441D0D3F6E8E76a4078f07f3581390d1b55` executes `claimAsset` for me.

Reading Smart Contracts chapter of [Polygon zkEVM documentation](https://docs.polygon.technology/zkEVM/architecture/protocol/zkevm-bridge/smart-contracts/#zkevm-smart-contract-interactions), I wonder if the 'periodicaly running process' is the Consensus Contract `PolygonZkEVM.sol`.

Could I additionally ask the following?

- what is `0xEaBCC441D0D3F6E8E76a4078f07f3581390d1b55`?
- what is the entity that periodically kicks off the process of building transaction batch and calls `claimAsset`?
- what is `0x084ad1...` that you used to retrieve the calldata?

**Comment by exfinen** [comment]
Thanks for your help @praetoriansentry!

**Comment by exfinen** [comment]
Thanks for your help @praetoriansentry!
