### ISSUE TITLE
[Inquiry] Is claiming asset on the L1 side from a script allowed?

### ISSUE THREAD

**Issue by exfinen** [0xPolygonHermez/zkevm-contracts#233]
Hello. 

I'm a developer developing a Polygon zkEVM bridge/claim library.
Thanks for helping me out [the last time](https://github.com/0xPolygonHermez/zkevm-contracts/issues/214) for bridging an asset from L1 to L2. 

Now I'm trying to bridge and claim an asset in the opposite direction (from L2 to L1) and having a problem.
Althrough I can claim a bridged asset from L1 side through [Polygon Portal](https://portal.polygon.technology/), I am unable to do so with a `claimAsset` call from a script.

In order to find out the diffence between the two cases:
1. First I waited until the bridged asset became ready-to-state in Polygon Portal.
2. Next I called `claimAsset` from a script and failed.
3. Then immediately after I confirmed the failure, I claimed the asset from Polygon Portal and succeded.

After that, comparing the `calldata` of [the failure case](https://sepolia.etherscan.io/tx/0x1362537c9f1f42cb4227a9c8ea24686479d5f91241bf9368c39462411abbe7a9) and [the successful case](https://sepolia.etherscan.io/tx/0xf3ce65a8a492367ba8549f9f7a01b250fa8cc8eff1aa07dbac2fa678db12b23a), I noticed that they were identical.

Does this mean only certain accounts are allowed to make the `claimAsset` call?

**Comment by omnifient** [comment]
hi @exfinen anyone can perform a claimAsset/claimMessage in both direction, it is not gated

took a quick glance at the 2 txs you linked, and one thing I noticed is that your failed tx has a 0.0000001 eth value passed (and the claim performed through the portal does not) - could that be the issue?

**Comment by exfinen** [comment]
Hi @omnifient. 

Your suggestion regarding the discrepancy in Ether values was insightful. It turned out that there were remnants of various trial and error left, and I was in a strange situation where, by mistake, the amount was set to 0 ETH, but in the metadata, I was setting the amount to 0.0000001 ETH.

After fixing the problem, I was able to claim an asset from a script. Thank you for your assistance.
