### ISSUE TITLE
Some doubt about bridgeAddress

### ISSUE THREAD

**Issue by Federico2014** [0xPolygonHermez/zkevm-contracts#256]
I get some doubt when reading the contract code.  Here,  when constructing the transaction to initialize the bridge on L2, I don't understand why the `bridgeAddress` used is the L1 bridge address, or is the `bridgeAddress` on L1 and L2 the same?

https://github.com/0xPolygonHermez/zkevm-contracts/blob/eecf908d75692d899049a6b4ba4507bd654d9fa1/contracts/v2/lib/PolygonRollupBaseEtrog.sol#L904

**Comment by Federico2014** [comment]
@invocamanman @krlosMata  Can you help me,  thanks

**Comment by hrasekj** [comment]
Can this be related with this note in kurtosis-cdk?
https://github.com/0xPolygon/kurtosis-cdk/blob/8c75b2443a2c38e0b3cb0bb733b42d3a6a410978/docs/how-to/use-native-token.md?plain=1#L175-L178

**Comment by Federico2014** [comment]
> Can this be related with this note in kurtosis-cdk? https://github.com/0xPolygon/kurtosis-cdk/blob/8c75b2443a2c38e0b3cb0bb733b42d3a6a410978/docs/how-to/use-native-token.md?plain=1#L175-L178

Not  relevant.

**Comment by Federico2014** [comment]
I finally realized the `bridgeAddress` on L1 and L2  for the polygon zkEvm is the same. so it is ok.
