### ISSUE TITLE
Allow any L1 provider

### ISSUE THREAD

**Issue by xavier-romero** [0xPolygonHermez/zkevm-contracts#272]
The ENV file requires this parameter:
`INFURA_PROJECT_ID`
And then builds the L1 URL like that:
`https://mainnet.infura.io/v3/${process.env.INFURA_PROJECT_ID}`
It would be useful to just accept the whole L1 URL in a var, like this:
`L1_URL`
So I can use whatever provider I wish, or even my own RPC node, instead of being forced to use Infura.

**Comment by krlosMata** [comment]
you can choose your own provider with `MAINNET_PROVIDER` environment var.
Here to choose from your provider or infura one: https://github.com/0xPolygonHermez/zkevm-contracts/blob/main/hardhat.config.ts#L144C30-L144C46
