### ISSUE TITLE
Failed tests

### ISSUE THREAD

**Issue by Federico2014** [0xPolygonHermez/zkevm-contracts#66]
I get the failures when I run `npm run test`. It seems the solidity and JS code are not consistent when calculate stark input 

Proof of efficiency snark stark input test
       Check commonjs unit test:

      AssertionError: expected '0x55f4c373d62dd577ef6160a1980130db83f…' to equal '0xd072c5e95f2a1aa8dee6f1e0667f72f9e66…'
      + expected - actual

      -0x55f4c373d62dd577ef6160a1980130db83f0686dab8afe5e32e641ca6abeab4c
      +0xd072c5e95f2a1aa8dee6f1e0667f72f9e66ed47f7ff5f5e3ad6f504379c73c26
      
      at Context.<anonymous> (test/contracts/snark_stark_input.test.js:77:36)
      at processTicksAndRejections (node:internal/process/task_queues:95:5)
      at runNextTicks (node:internal/process/task_queues:64:3)
      at listOnTimeout (node:internal/timers:533:9)
      at processTimers (node:internal/timers:507:7)

**Comment by krlosMata** [comment]
hi !!
tests are passing good if repository is downloaded from scratch:
```
git clone git@github.com:0xPolygonHermez/zkevm-contracts.git
cd zkevm-contracts
npm i
npm run test
``` 

if the repository was previously downloaded, it is probably a version issue with `package-lock.json` file.
Let me know if it works from scratch to you so we can close the issue

**Comment by Federico2014** [comment]
> hi

You are right. I have tried, and now it has passed. Thanks
